# Introduccion al modulo numpy

In [2]:
import numpy as np

Crear un arreglo numerico unidimensional que contenga digitos del 0 al 4

In [8]:
a1 = np.arange(0,5,1)

arreglo de tipo booleano de 4 filas y dos columnas que guarde solo `true`

In [9]:
np.full((4,2), True, dtype=bool)

array([[ True,  True],
       [ True,  True],
       [ True,  True],
       [ True,  True]])

Crear un arreglo 4x3 de tipo flotante lleno de unos

In [11]:
np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

matriz 2x2 con valores aleatorios

In [13]:
np.random.random((2,2))

array([[0.78682764, 0.72367229],
       [0.00947626, 0.61448946]])

crea una matriz de identidad 3x3

In [14]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [15]:
a1[2]

2

In [16]:
a1[-1]

4

In [19]:
A = np.array(
    [1,2,3,4,5,6]
)

B = np.array(
    [7,8,9,10,11,12]
)

C = np.add(A,B)

print(C)

[ 8 10 12 14 16 18]


In [21]:
D =  np.add(A,3)

print(D)

[4 5 6 7 8 9]


# Operaciones

+ `np.add`
+ `np.subtract`
+ `np.multiply`
+ `np.divide`
+ `np.sin`
+ `np.cos`
+ `np.log`
+ `np.sqrt`